### ISSUE TITLE
项目run不起来

### ISSUE THREAD

**Issue by metrue** [leancloud/LeanEngine-Full-Stack#19]
Hi, @wangxiao 

我正在尝试这个很不错的实验。可是我遇到安然README.md进行了之后，run "avoscloud" 的时候遇到如下错误，请您帮忙看一下。

提示：您可以敲入 rs 命令并回车来重启本进程
提示：您可以使用 http://localhost:3001 测试 Cloud 函数

> LeanEngine-Full-Stack@1.0.0 start /Users/huangmh/Codes/LeanEngine-Full-Stack
> node --harmony server.js

/Users/huangmh/Codes/LeanEngine-Full-Stack/server-modules/app.js:38
app.use((req, res, next) => {
                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/huangmh/Codes/LeanEngine-Full-Stack/server.js:21:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! LeanEngine-Full-Stack@1.0.0 start: `node --harmony server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the LeanEngine-Full-Stack@1.0.0 start script.
npm ERR! This is most likely a problem with the LeanEngine-Full-Stack package,

**Comment by metrue** [comment]
使用 babel 编译了之后可以使用，所以问题是ES6环境没有搭建好了吗

**Comment by wangxiao** [comment]
hi，你好，这个问题应该是 nodejs 版本问题，建议你改到 nodejs 0.12.x 版本试一下。

**Comment by metrue** [comment]
@wangxiao 

是的，谢谢了。closed.
